### ISSUE TITLE
display progress bar

### ISSUE THREAD

**Issue by Gummibeer** [gotkrypto76/SteamAchievementManager#2]
display a progress bar during processing all games to know about the current state.

**Comment by gotkrypto76** [comment]
Hey there,

I have already implemented a progress bar for this, though it doesn’t stand out real well. You can find it on the bottom right of the window with the “Unlock All” button.

Appreciate the feedback,
GotKrypto

**Comment by Gummibeer** [comment]
Ok, I found it - it's where all other progress bar's are also - I searched for a pop-up window but this is also good! :)
